changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - question
      - wontfix
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: New Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - dependencies
        - ci
        - release
    - title: Other Changes
      labels:
        - '*'
