[package]
name = "remote-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
logging-core = { path = "../logging-core" }
serde.workspace = true
serde_json.workspace = true
ssh2 = "0.9.5"
suppaftp = { version = "11.0.0", default-features = false, features = ["default"] }
ureq = "3.4.0"
