/** Lucide icons for session toolbar command ids (presentation only). */

import {
  ArrowDownToLine,
  ArrowLeftFromLine,
  ArrowLeftRight,
  ArrowRightFromLine,
  ArrowUpToLine,
  Asterisk,
  Briefcase,
  Check,
  CircleX,
  Copy,
  Diff,
  Equal,
  EqualApproximately,
  Eye,
  FileStack,
  FileType,
  FoldVertical,
  Funnel,
  GitMerge,
  Home,
  ListChecks,
  ListTree,
  Play,
  PlayCircle,
  RefreshCw,
  RotateCw,
  Rows2,
  Scale,
  Type,
  UnfoldVertical,
  X,
  type LucideIcon,
} from '@lucide/vue'

/**
 * Map known toolbar command ids to existing Lucide icons.
 * Unknown ids fall back to the letter glyph in the shell — do not invent misleading icons.
 */
export const sessionToolbarIcons: Readonly<Record<string, LucideIcon>> = {
  home: Home,
  sessions: Briefcase,
  all: Asterisk,
  diffs: Diff,
  same: Equal,
  structure: ListTree,
  context: Rows2,
  minor: EqualApproximately,
  rules: Scale,
  format: FileType,
  font: Type,
  copy: Copy,
  expand: UnfoldVertical,
  collapse: FoldVertical,
  select: ListChecks,
  files: FileStack,
  refresh: RefreshCw,
  swap: ArrowLeftRight,
  stop: CircleX,
  filters: Funnel,
  peek: Eye,
  'next-section': ArrowDownToLine,
  'prev-section': ArrowUpToLine,
  'next-diff': ArrowDownToLine,
  'prev-diff': ArrowUpToLine,
  reload: RotateCw,
  'sync-now': Play,
  cancel: X,
  accept: Check,
  'same-ok': Check,
  merge: GitMerge,
  'to-output': ArrowRightFromLine,
  play2: PlayCircle,
  'favor-left': ArrowLeftFromLine,
  'favor-right': ArrowRightFromLine,
  'next-conflict': ArrowDownToLine,
  'prev-conflict': ArrowUpToLine,
}

export function iconForSessionToolbarCommand(id: string): LucideIcon | undefined {
  return sessionToolbarIcons[id]
}
