[package]
name = "script-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
diff-core = { path = "../diff-core" }
file-core = { path = "../file-core" }
folder-core = { path = "../folder-core" }
job-core = { path = "../job-core" }
logging-core = { path = "../logging-core" }
media-core = { path = "../media-core" }
hex-core = { path = "../hex-core" }
image-core = { path = "../image-core" }
report-core = { path = "../report-core" }
serde.workspace = true
serde_json.workspace = true
shared-types = { path = "../shared-types" }
snapshot-core = { path = "../snapshot-core" }
sync-core = { path = "../sync-core" }
archive-core = { path = "../archive-core" }
folder-merge-core = { path = "../folder-merge-core" }
